// sentiment phrase list for financial headlines

const phraseSentiments = [
  // --- Bullish phrases ---
  { phrase: "acquisition completed", score: 2 },
  { phrase: "strategic acquisition", score: 2 },
  { phrase: "merger approved", score: 2 },
  { phrase: "acquires stake", score: 2 },
  { phrase: "posts strong earnings", score: 2 },
  { phrase: "blowout earnings", score: 2 },
  { phrase: "earnings beat", score: 2 },
  { phrase: "tops forecasts", score: 2 },
  { phrase: "raises dividend", score: 2 },
  { phrase: "launches buyback", score: 2 },
  { phrase: "expands footprint", score: 2 },
  { phrase: "penetrates market", score: 2 },
  { phrase: "new partnerships", score: 2 },
  { phrase: "partners with", score: 2 },
  { phrase: "secures contract", score: 2 },
  { phrase: "increased revenue", score: 2 },
  { phrase: "adds customers", score: 1 },
  { phrase: "new funding round", score: 1 },
  { phrase: "new market entry", score: 1 },
  { phrase: "exclusive deal", score: 2 },
  { phrase: "achieves milestone", score: 2 },
  { phrase: "accelerates", score: 2 },
  { phrase: "overdelivers", score: 2 },
  { phrase: "new record", score: 2 },
  { phrase: "record-breaking", score: 2 },
  { phrase: "stronger than expected", score: 2 },
  { phrase: "guidance above consensus", score: 2 },
  { phrase: "rising demand", score: 2 },
  { phrase: "improved efficiency", score: 1 },
  { phrase: "margin expansion", score: 1 },
  { phrase: "significant upside", score: 2 },
  { phrase: "bull run", score: 2 },
  { phrase: "regulatory greenlight", score: 2 },

  // Additional bullish coverage:
  { phrase: "beats expectations", score: 2 },
  { phrase: "beats estimates", score: 2 },
  { phrase: "tops estimates", score: 2 },
  { phrase: "exceeds expectations", score: 2 },
  { phrase: "raises outlook", score: 2 },
  { phrase: "raises guidance", score: 2 },
  { phrase: "upgrades", score: 2 },
  { phrase: "record high", score: 2 },
  { phrase: "record profit", score: 2 },
  { phrase: "strong quarter", score: 2 },
  { phrase: "surge", score: 2 },
  { phrase: "soars", score: 2 },
  { phrase: "rallies", score: 2 },
  { phrase: "jumps", score: 2 },
  { phrase: "gains", score: 2 },
  { phrase: "expands", score: 1 },
  { phrase: "growth", score: 1 },
  { phrase: "improves", score: 1 },
  { phrase: "strengthens", score: 1 },
  { phrase: "bullish", score: 2 },
  { phrase: "positive", score: 1 },
  { phrase: "strong demand", score: 2 },
  { phrase: "increases dividend", score: 2 },
  { phrase: "initiates dividend", score: 2 },
  { phrase: "approves buyback", score: 2 },
  { phrase: "secures funding", score: 1 },
  { phrase: "wins contract", score: 2 },
  { phrase: "acquisition", score: 2 },
  { phrase: "merger", score: 2 },
  { phrase: "regulatory approval", score: 2 },
  { phrase: "launches product", score: 2 },
  { phrase: "launches service", score: 2 },
  { phrase: "outperforms", score: 2 },
  { phrase: "posts profit", score: 2 },
  { phrase: "returns to profit", score: 2 },
  { phrase: "rebound", score: 2 },
  { phrase: "recovery", score: 2 },
  { phrase: "restores", score: 1 },
  { phrase: "recovers", score: 1 },
  { phrase: "confirms uptrend", score: 2 },
  { phrase: "confirms support", score: 1 },
  { phrase: "receives investment", score: 1 },
  { phrase: "new partnership", score: 1 },
  { phrase: "positive outlook", score: 2 },
  { phrase: "resumes growth", score: 1 },
  { phrase: "raises target", score: 1 },
  { phrase: "raises price target", score: 1 },
  { phrase: "initiates coverage with buy", score: 2 },
  { phrase: "initiates with outperform", score: 2 },
  { phrase: "initiates with overweight", score: 2 },
  { phrase: "announces buyback", score: 2 },
  { phrase: "announces dividend", score: 2 },
  { phrase: "increases forecast", score: 1 },
  { phrase: "improves rating", score: 1 },
  { phrase: "upward revision", score: 1 },
  { phrase: "raises eps", score: 2 },
  { phrase: "raises revenue", score: 2 },
  { phrase: "reaffirms guidance", score: 1 },
  { phrase: "offers upbeat forecast", score: 1 },
  { phrase: "restores dividend", score: 1 },
  { phrase: "secures approval", score: 1 },
  { phrase: "posts record sales", score: 2 },
  { phrase: "posts record revenue", score: 2 },
  { phrase: "posts record earnings", score: 2 },
  { phrase: "accelerates growth", score: 1 },
  { phrase: "acquires", score: 2 },
  { phrase: "completes acquisition", score: 2 },
  { phrase: "strategic alliance", score: 1 },
  { phrase: "strategic partnership", score: 1 },
  { phrase: "approved", score: 1 },
  { phrase: "receives approval", score: 1 },
  { phrase: "receives clearance", score: 1 },
  { phrase: "fda approval", score: 2 },
  { phrase: "launches ipo", score: 1 },
  { phrase: "listed on exchange", score: 1 },
  { phrase: "positive trial results", score: 2 },
  { phrase: "breakthrough", score: 2 },
  { phrase: "wins lawsuit", score: 1 },
  { phrase: "settles favorably", score: 1 },
  { phrase: "positive earnings", score: 2 },
  { phrase: "positive surprise", score: 2 },
  { phrase: "strong performance", score: 2 },
  { phrase: "robust results", score: 2 },
  { phrase: "unexpected gain", score: 1 },
  { phrase: "unexpected profit", score: 1 },
  { phrase: "unexpectedly strong", score: 2 },
  { phrase: "turnaround", score: 2 },
  { phrase: "comeback", score: 1 },
  { phrase: "initiates share buyback", score: 2 },
  { phrase: "receives grant", score: 1 },
  { phrase: "receives award", score: 1 },
  { phrase: "wins award", score: 1 },
  { phrase: "wins bid", score: 1 },
  { phrase: "secures deal", score: 2 },
  { phrase: "signs agreement", score: 1 },
  { phrase: "receives order", score: 1 },
  { phrase: "new customer", score: 1 },
  { phrase: "expanding footprint", score: 2 },
  { phrase: "expanding globally", score: 2 },
  { phrase: "expanding internationally", score: 2 },
  { phrase: "expanding market", score: 1 },
  { phrase: "expanding capacity", score: 1 },
  { phrase: "raises funding", score: 1 },
  { phrase: "attracts investment", score: 1 },
  { phrase: "secures investment", score: 1 },
  { phrase: "backs", score: 1 },
  { phrase: "endorsed", score: 1 },
  { phrase: "high demand", score: 2 },
  { phrase: "record demand", score: 2 },
  { phrase: "unveils", score: 1 },
  { phrase: "introduces", score: 1 },
  { phrase: "debuts", score: 1 },
  { phrase: "rolls out", score: 1 },
  { phrase: "clinches deal", score: 1 },
  { phrase: "delivers strong", score: 1 },
  { phrase: "delivers record", score: 1 },
  { phrase: "surpasses", score: 1 },
  { phrase: "smashes", score: 1 },
  { phrase: "crushes", score: 1 },
  { phrase: "outpaces", score: 1 },
  { phrase: "improves margins", score: 1 },
  { phrase: "increases margins", score: 1 },
  { phrase: "boosts", score: 1 },
  { phrase: "boosts guidance", score: 1 },
  { phrase: "extends rally", score: 1 },
  { phrase: "continues rally", score: 1 },
  { phrase: "sustained growth", score: 1 },
  { phrase: "new product launch", score: 2 },
  { phrase: "expansion plans", score: 2 },
  { phrase: "profit up", score: 2 },
  { phrase: "revenue up", score: 2 },
  { phrase: "new highs", score: 2 },
  { phrase: "upgrades outlook", score: 2 },
  { phrase: "project approved", score: 2 },
  { phrase: "granted approval", score: 2 },
  { phrase: "accelerating growth", score: 2 },
  { phrase: "institutional buying", score: 2 },
  { phrase: "bullish guidance", score: 2 },
  { phrase: "hikes dividend", score: 2 },
  { phrase: "hikes forecast", score: 2 },
  { phrase: "raises price objective", score: 2 },
  { phrase: "initiates outperform", score: 2 },
  { phrase: "initiates buy", score: 2 },
  { phrase: "share repurchase", score: 2 },

  // --- Bearish phrases ---
  { phrase: "profit warning", score: -2 },
  { phrase: "misses expectations", score: -2 },
  { phrase: "misses estimates", score: -2 },
  { phrase: "falls short", score: -2 },
  { phrase: "misses forecast", score: -2 },
  { phrase: "cuts outlook", score: -2 },
  { phrase: "cuts guidance", score: -2 },
  { phrase: "downgrades", score: -2 },
  { phrase: "record low", score: -2 },
  { phrase: "record loss", score: -2 },
  { phrase: "weak quarter", score: -2 },
  { phrase: "slump", score: -2 },
  { phrase: "plunges", score: -2 },
  { phrase: "tumbles", score: -2 },
  { phrase: "slides", score: -2 },
  { phrase: "drops", score: -2 },
  { phrase: "loses", score: -2 },
  { phrase: "contraction", score: -2 },
  { phrase: "declines", score: -2 },
  { phrase: "deteriorates", score: -2 },
  { phrase: "weakens", score: -2 },
  { phrase: "bearish", score: -2 },
  { phrase: "negative", score: -1 },
  { phrase: "weak demand", score: -2 },
  { phrase: "cuts dividend", score: -2 },
  { phrase: "suspends dividend", score: -2 },
  { phrase: "cancels buyback", score: -2 },
  { phrase: "shrinks operations", score: -2 },
  { phrase: "loses contract", score: -2 },
  { phrase: "failed acquisition", score: -2 },
  { phrase: "regulatory setback", score: -2 },
  { phrase: "product recall", score: -2 },
  { phrase: "service outage", score: -2 },
  { phrase: "underperforms", score: -2 },
  { phrase: "posts loss", score: -2 },
  { phrase: "posts decline", score: -2 },
  { phrase: "returns to loss", score: -2 },
  { phrase: "downturn", score: -2 },
  { phrase: "recession", score: -2 },
  { phrase: "downgraded", score: -2 },
  { phrase: "faces lawsuit", score: -2 },
  { phrase: "investigation", score: -2 },
  { phrase: "probe", score: -2 },
  { phrase: "regulatory probe", score: -2 },
  { phrase: "delays", score: -2 },
  { phrase: "delay in", score: -2 },
  { phrase: "delayed", score: -2 },
  { phrase: "missed deadline", score: -2 },
  { phrase: "withdraws guidance", score: -2 },
  { phrase: "withdraws outlook", score: -2 },
  { phrase: "negative outlook", score: -2 },
  { phrase: "lowers target", score: -2 },
  { phrase: "lowers price target", score: -2 },
  { phrase: "initiates coverage with sell", score: -2 },
  { phrase: "initiates with underperform", score: -2 },
  { phrase: "initiates with underweight", score: -2 },
  { phrase: "announces layoff", score: -2 },
  { phrase: "cutting jobs", score: -2 },
  { phrase: "job cuts", score: -2 },
  { phrase: "reduces workforce", score: -2 },
  { phrase: "reducing staff", score: -2 },
  { phrase: "cuts forecast", score: -2 },
  { phrase: "lowers forecast", score: -2 },
  { phrase: "reduces eps", score: -2 },
  { phrase: "reduces revenue", score: -2 },
  { phrase: "downward revision", score: -2 },
  { phrase: "misses eps", score: -2 },
  { phrase: "misses revenue", score: -2 },
  { phrase: "cuts rating", score: -2 },
  { phrase: "downgrades rating", score: -2 },
  { phrase: "earnings warning", score: -2 },
  { phrase: "negative earnings", score: -2 },
  { phrase: "negative surprise", score: -2 },
  { phrase: "weak performance", score: -2 },
  { phrase: "disappointing results", score: -2 },
  { phrase: "unexpected loss", score: -2 },
  { phrase: "unexpected decline", score: -2 },
  { phrase: "unexpectedly weak", score: -2 },
  { phrase: "bankruptcy", score: -3 },
  { phrase: "files for bankruptcy", score: -3 },
  { phrase: "chapter 11", score: -2 },
  { phrase: "restructuring", score: -2 },
  { phrase: "default", score: -2 },
  { phrase: "missed payment", score: -2 },
  { phrase: "defaults on", score: -2 },
  { phrase: "misses coupon", score: -2 },
  { phrase: "misses payment", score: -2 },
  { phrase: "investigated", score: -2 },
  { phrase: "fined", score: -2 },
  { phrase: "penalized", score: -2 },
  { phrase: "lawsuit filed", score: -2 },
  { phrase: "settles unfavorably", score: -2 },
  { phrase: "loses lawsuit", score: -2 },
  { phrase: "loses bid", score: -2 },
  { phrase: "loses order", score: -2 },
  { phrase: "customer loss", score: -2 },
  { phrase: "loses customer", score: -2 },
  { phrase: "recall", score: -2 },
  { phrase: "product failure", score: -2 },
  { phrase: "service failure", score: -2 },
  { phrase: "market contraction", score: -2 },
  { phrase: "shrinking market", score: -2 },
  { phrase: "market exit", score: -2 },
  { phrase: "exits market", score: -2 },
  { phrase: "closes operations", score: -2 },
  { phrase: "facility closure", score: -2 },
  { phrase: "plant closure", score: -2 },
  { phrase: "shuts down", score: -2 },
  { phrase: "suspends operations", score: -2 },
  { phrase: "halts operations", score: -2 },
  { phrase: "cuts production", score: -2 },
  { phrase: "reduces capacity", score: -2 },
  { phrase: "cutbacks", score: -2 },
  { phrase: "warns", score: -2 },
  { phrase: "warning", score: -2 },
  { phrase: "regulatory action", score: -2 },
  { phrase: "regulatory ban", score: -2 },
  { phrase: "banned", score: -2 },
  { phrase: "delisted", score: -2 },
  { phrase: "trading halt", score: -2 },
  { phrase: "share suspension", score: -2 },
  { phrase: "fraud", score: -3 },
  { phrase: "scandal", score: -3 },
  { phrase: "corruption", score: -2 },
  { phrase: "whistleblower", score: -2 },
  { phrase: "embezzlement", score: -2 },
  { phrase: "data breach", score: -2 },
  { phrase: "hack", score: -2 },
  { phrase: "cyberattack", score: -2 },
  { phrase: "layoffs", score: -2 },
  { phrase: "retrenchment", score: -2 },
  { phrase: "furlough", score: -2 },
  { phrase: "strike", score: -2 },
  { phrase: "walkout", score: -2 },
  { phrase: "labor dispute", score: -2 },
  { phrase: "union action", score: -2 },
  { phrase: "supply shortage", score: -2 },
  { phrase: "supply disruption", score: -2 },
  { phrase: "inventory build", score: -2 },
  { phrase: "overcapacity", score: -2 },
  { phrase: "misses deadline", score: -2 },
  { phrase: "delays launch", score: -2 },
  { phrase: "delays approval", score: -2 },
  { phrase: "suspends dividend", score: -2 },
  { phrase: "cuts dividend", score: -2 },
  { phrase: "reduces dividend", score: -2 },
  { phrase: "suspends payment", score: -2 },
  { phrase: "cuts payment", score: -2 },
  { phrase: "reduces payment", score: -2 },
  { phrase: "pulls product", score: -2 },
  { phrase: "discontinues", score: -2 },
  { phrase: "terminated", score: -2 },
  { phrase: "termination", score: -2 },
  { phrase: "cancels", score: -2 },
  { phrase: "cancellation", score: -2 },
  { phrase: "sues", score: -2 },
  { phrase: "faces charges", score: -2 },
  { phrase: "criminal charges", score: -2 },
  { phrase: "civil charges", score: -2 },
  { phrase: "regulatory fine", score: -2 },
  { phrase: "antitrust investigation", score: -2 },
  { phrase: "delisting risk", score: -2 },
  { phrase: "shareholder lawsuit", score: -2 },
  { phrase: "profit plunges", score: -2 },
  { phrase: "profit falls", score: -2 },
  { phrase: "profit down", score: -2 },
  { phrase: "revenue down", score: -2 },
  { phrase: "income down", score: -2 },
  { phrase: "cuts jobs", score: -2 },
  { phrase: "mass layoffs", score: -2 },
  { phrase: "exodus", score: -2 },
  { phrase: "leadership shakeup", score: -2 },
  { phrase: "insider selling", score: -2 },
  { phrase: "restatement", score: -2 },
  { phrase: "restates earnings", score: -2 },
  { phrase: "audit issue", score: -2 },
  { phrase: "governance issue", score: -2 },
  { phrase: "missed payment", score: -2 },
  { phrase: "dividend cut", score: -2 },
  { phrase: "interest rate hike", score: -1 },
  { phrase: "policy tightening", score: -1 },
  { phrase: "geopolitical tension", score: -2 },
  { phrase: "trade war", score: -2 },
  { phrase: "tariff imposed", score: -2 },
  { phrase: "currency devaluation", score: -2 },
  { phrase: "inflation surge", score: -2 },
  { phrase: "stagflation", score: -2 },
  { phrase: "systemic risk", score: -2 },
  { phrase: "market rout", score: -2 },
  { phrase: "market crash", score: -3 }
];

// Fallback single word/short phrase lists
const fallbackBullish = [
  "soar", "rise", "gain", "surge", "up", "record", "growth", "strong", "bull", "beat", "rally", "jump", "increase", "expand", "rebound", "outperform", "profit", "boost", "improve", "positive", "win", "approve", "acquire", "secure", "recover", "comeback", "dividend", "buyback", "milestone", "partnership", "award", "launch", "achievement"
];
const fallbackBearish = [
  "fall", "drop", "decline", "down", "slump", "loss", "weak", "bear", "miss", "plunge", "crash", "decrease", "layoff", "recall", "probe", "cut", "warn", "negative", "default", "investigation", "lawsuit", "delay", "downgrade", "fined", "scandal", "suspend", "terminate", "halt", "shut", "strike", "bankruptcy", "restatement", "outage"
];

// Main function
function getSentiment(headline) {
  const text = headline.toLowerCase();
  let score = 0;

  for (const { phrase, score: phraseScore } of phraseSentiments) {
    if (text.includes(phrase)) score += phraseScore;
  }

  if (score === 0) {
    fallbackBullish.forEach(word => { if (text.includes(word)) score += 1; });
    fallbackBearish.forEach(word => { if (text.includes(word)) score -= 1; });
  }

  if (score > 0) return "Bullish";
  if (score < 0) return "Bearish";
  return "Neutral";
}