// sentiment phrase list for financial headlines

const phraseSentiments = [
  // --- Bullish phrases ---
  { phrase: "acquisition completed", score: 2 },
  { phrase: "strategic acquisition", score: 2 },
  { phrase: "merger approved", score: 2 },
  { phrase: "profit accelerates", score: 2 },
  { phrase: "profits soar", score: 2 },
  { phrase: "robust outlook", score: 2 },
  { phrase: "optimistic forecast", score: 2 },
  { phrase: "market leadership", score: 2 },
  { phrase: "leads sector", score: 2 },
  { phrase: "positive sentiment", score: 1 },
  { phrase: "market outperformance", score: 2 },
  { phrase: "capital inflow", score: 1 },
  { phrase: "solid fundamentals", score: 1 },
  { phrase: "resilient results", score: 1 },
  { phrase: "growth trajectory", score: 2 },
  { phrase: "dividend hike", score: 2 },
  { phrase: "beats revenue forecast", score: 2 },
  { phrase: "record cash flow", score: 2 },
  { phrase: "record margins", score: 2 },
  { phrase: "all-time high", score: 2 },
  { phrase: "unprecedented demand", score: 2 },
  { phrase: "outpaces industry", score: 2 },
  { phrase: "margin improvement", score: 1 },
  { phrase: "raises capital", score: 1 },
  { phrase: "new contracts", score: 1 },
  { phrase: "new clients", score: 1 },
  { phrase: "award winner", score: 1 },
  { phrase: "industry leader", score: 2 },
  { phrase: "price target raised", score: 1 },
  { phrase: "share price climbs", score: 2 },
  { phrase: "expanding operations", score: 1 },
  { phrase: "capacity increase", score: 1 },
  { phrase: "positive cash flow", score: 2 },
  { phrase: "cash reserves rise", score: 1 },
  { phrase: "debt reduced", score: 1 },
  { phrase: "strategic investment", score: 2 },
  { phrase: "broadening portfolio", score: 1 },
  { phrase: "notable gains", score: 1 },
  { phrase: "overweight rating", score: 1 },
  { phrase: "upward momentum", score: 2 },
  { phrase: "sustained rally", score: 2 },
  { phrase: "growing market share", score: 2 },
  { phrase: "business expansion", score: 1 },
  { phrase: "favorable ruling", score: 1 },
  { phrase: "favorable conditions", score: 1 },
  { phrase: "record-breaking sales", score: 2 },
  { phrase: "better than forecast", score: 2 },
  { phrase: "increased guidance", score: 2 },
  { phrase: "lifted estimates", score: 1 },
  { phrase: "positive revisions", score: 1 },
  { phrase: "rising profits", score: 2 },
  { phrase: "surpassing forecasts", score: 2 },
  { phrase: "double-digit growth", score: 2 },
  { phrase: "sustained profitability", score: 1 },
  { phrase: "diversification", score: 1 },
  { phrase: "increased market cap", score: 2 },
  { phrase: "market optimism", score: 1 },
  { phrase: "bullish reversal", score: 2 },
  { phrase: "securing new deals", score: 2 },
  { phrase: "cash dividends", score: 2 },
  { phrase: "credit upgrade", score: 1 },
  { phrase: "upbeat projections", score: 2 },
  { phrase: "innovative products", score: 2 },
  { phrase: "breakout performance", score: 2 },
  { phrase: "industry accolades", score: 1 },
  { phrase: "improved ratings", score: 1 },
  { phrase: "sales momentum", score: 2 },
  { phrase: "new highs achieved", score: 2 },
  { phrase: "buyback program", score: 2 },
  { phrase: "analyst upgrade", score: 2 },
  { phrase: "overweight recommendation", score: 1 },
  { phrase: "bullish momentum", score: 2 },
  { phrase: "record shipment", score: 2 },
  { phrase: "expanding presence", score: 1 },
  { phrase: "increasing order book", score: 2 },
  { phrase: "positive earnings surprise", score: 2 },
  { phrase: "premium product launch", score: 1 },
  { phrase: "growing customer base", score: 2 },
  { phrase: "market entry", score: 1 },
  { phrase: "revenue acceleration", score: 2 },
  { phrase: "favorable trend", score: 1 },
  { phrase: "healthy balance sheet", score: 2 },
  { phrase: "rising asset value", score: 1 },
  { phrase: "expanding distribution", score: 1 },
  { phrase: "increased liquidity", score: 2 },
  { phrase: "raising forecasts", score: 1 },
  { phrase: "record quarterly results", score: 2 },
  { phrase: "higher guidance", score: 2 },
  { phrase: "sustainable growth", score: 2 },
  { phrase: "robust cash position", score: 1 },
  { phrase: "industry outperformance", score: 2 },
  { phrase: "new market lead", score: 1 },
  { phrase: "emerging markets growth", score: 2 },
  { phrase: "sales exceed expectations", score: 2 },
  { phrase: "shareholder return", score: 1 },
  { phrase: "consistent profitability", score: 1 },
  { phrase: "growing backlog", score: 1 },
  { phrase: "best-in-class", score: 2 },
  { phrase: "sector leader", score: 2 },
  { phrase: "expanding customer reach", score: 1 },
  { phrase: "innovative strategy", score: 1 },
  { phrase: "broadening footprint", score: 1 },
  { phrase: "all-time record", score: 2 },
  { phrase: "strong order intake", score: 2 },
  { phrase: "greater efficiency", score: 1 },
  { phrase: "improved operations", score: 1 },
  { phrase: "upside potential", score: 2 },
  { phrase: "positive institutional outlook", score: 1 },
  { phrase: "renewed growth", score: 1 },
  { phrase: "pipeline expansion", score: 1 },
  { phrase: "margin recovery", score: 1 },
  { phrase: "growth outlook", score: 2 },
  { phrase: "profitability milestone", score: 2 },
  { phrase: "demand spike", score: 2 },
  { phrase: "digital transformation", score: 1 },
  { phrase: "increasing dividends", score: 2 },
  { phrase: "record order book", score: 2 },
  { phrase: "stellar results", score: 2 },
  { phrase: "turns profitable", score: 2 },
  { phrase: "partnership expansion", score: 1 },
  { phrase: "launching new division", score: 1 },
  { phrase: "order backlog grows", score: 1 },
  { phrase: "record net income", score: 2 },
  { phrase: "solid pipeline", score: 1 },
  { phrase: "enhanced shareholder value", score: 1 },
  { phrase: "earnings surprise", score: 2 },
  { phrase: "outperforming", score: 2 },
  { phrase: "strong brand recognition", score: 1 },
  { phrase: "long-term growth", score: 1 },
  { phrase: "increases projection", score: 1 },
  { phrase: "bright outlook", score: 2 },
  { phrase: "positive sentiment shift", score: 1 },
  { phrase: "uptrend", score: 2 },
  { phrase: "expanding into new markets", score: 1 },
  { phrase: "market share gain", score: 1 },
  { phrase: "positive inflow", score: 1 },
  { phrase: "growth engine", score: 2 },
  { phrase: "raised estimate", score: 1 },
  { phrase: "improved returns", score: 1 },
  { phrase: "record net sales", score: 2 },
  { phrase: "accelerating earnings", score: 2 },
  { phrase: "increased utilization", score: 1 },
  { phrase: "higher asset quality", score: 1 },
  { phrase: "cash flow positive", score: 2 },
  { phrase: "diversified growth", score: 1 },
  { phrase: "driving innovation", score: 1 },
  { phrase: "expanding platform", score: 1 },
  { phrase: "growing segment", score: 1 },
  { phrase: "net profit up", score: 2 },
  { phrase: "earnings per share up", score: 2 },
  { phrase: "project wins", score: 1 },
  { phrase: "strong liquidity", score: 2 },
  { phrase: "outlook upgrade", score: 1 },
  { phrase: "higher occupancy", score: 1 },
  { phrase: "partnership signed", score: 1 },
  { phrase: "improved forecast", score: 1 },
  { phrase: "demand recovery", score: 2 },
  { phrase: "market expansion", score: 1 },
  { phrase: "improved sales", score: 1 },
  { phrase: "asset acquisition", score: 1 },
  { phrase: "resilience", score: 1 },
  { phrase: "favorable forecast", score: 1 },
  { phrase: "margin gains", score: 1 },
  { phrase: "positive guidance", score: 2 },
  { phrase: "margin growth", score: 1 },
  { phrase: "new revenue streams", score: 1 },
  { phrase: "strong fundamentals", score: 2 },
  { phrase: "growth capital", score: 1 },
  { phrase: "rising EPS", score: 2 },
  { phrase: "exceeding guidance", score: 2 },
  { phrase: "top-line growth", score: 2 },
  { phrase: "bottom-line growth", score: 2 },
  { phrase: "shareholder value creation", score: 1 },
  { phrase: "rising asset prices", score: 1 },
  { phrase: "market leadership position", score: 2 },
  { phrase: "capital appreciation", score: 1 },
  { phrase: "positive net income", score: 2 },
  { phrase: "record-breaking profits", score: 2 },
  { phrase: "expanding workforce", score: 1 },
  { phrase: "new distribution agreement", score: 1 },
  { phrase: "brand expansion", score: 1 },
  { phrase: "premium valuation", score: 1 },
  { phrase: "industry recognition", score: 1 },
  { phrase: "attracts investors", score: 1 },
  { phrase: "increased investment", score: 1 },
  { phrase: "successful launch", score: 2 },
  { phrase: "over-delivers", score: 2 },
  { phrase: "exceeds target", score: 2 },
  { phrase: "positive direction", score: 1 },
  { phrase: "rising revenue", score: 2 },
  { phrase: "healthy pipeline", score: 1 },
  { phrase: "robust pipeline", score: 2 },
  { phrase: "solid quarter", score: 1 },
  { phrase: "improved cash generation", score: 1 },
  { phrase: "new business wins", score: 1 },
  { phrase: "market enthusiasm", score: 1 },
  { phrase: "business momentum", score: 1 },
  { phrase: "consistent outperformance", score: 2 },
  { phrase: "steady growth", score: 1 },
  { phrase: "surged", score: 2 },
  { phrase: "bullish sentiment", score: 1 },
  { phrase: "project approved", score: 2 },
  { phrase: "capital raise", score: 1 },
  { phrase: "industry tailwinds", score: 1 },
  { phrase: "improved leverage", score: 1 },
  { phrase: "profit growth", score: 2 },
  { phrase: "credit positive", score: 1 },
  { phrase: "profit beats", score: 2 },
  { phrase: "strong franchise", score: 1 },
  { phrase: "operational excellence", score: 1 },
  { phrase: "synergy realization", score: 1 },
  { phrase: "cost efficiencies", score: 1 },
  { phrase: "asset appreciation", score: 1 },
  { phrase: "record operating income", score: 2 },
  { phrase: "credit rating upgrade", score: 1 },
  { phrase: "operational improvement", score: 1 },
  { phrase: "product innovation", score: 1 },
  { phrase: "revenue enhancement", score: 1 },
  { phrase: "expanding asset base", score: 1 },
  { phrase: "portfolio diversification", score: 1 },
  { phrase: "revenue beats", score: 2 },
  { phrase: "contract extension", score: 1 },
  { phrase: "capital gains", score: 1 },
  { phrase: "accretive acquisition", score: 2 },
  { phrase: "enhanced offering", score: 1 },
  { phrase: "capital deployment", score: 1 },
  { phrase: "operational leverage", score: 1 },
  { phrase: "operating leverage", score: 1 },
  { phrase: "improved utilization", score: 1 },
  { phrase: "higher volumes", score: 1 },
  { phrase: "revenue uplift", score: 1 },
  { phrase: "share price appreciation", score: 2 },
  { phrase: "breaks resistance", score: 2 },
  { phrase: "analyst reiterates buy", score: 2 },
  { phrase: "initiates coverage buy", score: 2 },
  { phrase: "record order intake", score: 2 },
  { phrase: "expanding supplier base", score: 1 },
  { phrase: "improved asset quality", score: 1 },
  { phrase: "growing sales", score: 2 },
  { phrase: "profit margin expansion", score: 2 },
  { phrase: "net income grows", score: 2 },
  { phrase: "new peaks", score: 2 }
  { phrase: "acquires stake", score: 2 },
  { phrase: "posts strong earnings", score: 2 },
  { phrase: "blowout earnings", score: 2 },
  { phrase: "earnings beat", score: 2 },
  { phrase: "tops forecasts", score: 2 },
  { phrase: "raises dividend", score: 2 },
  { phrase: "launches buyback", score: 2 },
  { phrase: "expands footprint", score: 2 },
  { phrase: "penetrates market", score: 2 },
  { phrase: "new partnerships", score: 2 },
  { phrase: "partners with", score: 2 },
  { phrase: "secures contract", score: 2 },
  { phrase: "increased revenue", score: 2 },
  { phrase: "adds customers", score: 1 },
  { phrase: "new funding round", score: 1 },
  { phrase: "new market entry", score: 1 },
  { phrase: "exclusive deal", score: 2 },
  { phrase: "achieves milestone", score: 2 },
  { phrase: "accelerates", score: 2 },
  { phrase: "overdelivers", score: 2 },
  { phrase: "new record", score: 2 },
  { phrase: "record-breaking", score: 2 },
  { phrase: "stronger than expected", score: 2 },
  { phrase: "guidance above consensus", score: 2 },
  { phrase: "rising demand", score: 2 },
  { phrase: "improved efficiency", score: 1 },
  { phrase: "margin expansion", score: 1 },
  { phrase: "significant upside", score: 2 },
  { phrase: "bull run", score: 2 },
  { phrase: "regulatory greenlight", score: 2 },

  // Additional bullish coverage:
  { phrase: "beats expectations", score: 2 },
  { phrase: "beats estimates", score: 2 },
  { phrase: "tops estimates", score: 2 },
  { phrase: "exceeds expectations", score: 2 },
  { phrase: "raises outlook", score: 2 },
  { phrase: "raises guidance", score: 2 },
  { phrase: "upgrades", score: 2 },
  { phrase: "record high", score: 2 },
  { phrase: "record profit", score: 2 },
  { phrase: "strong quarter", score: 2 },
  { phrase: "surge", score: 2 },
  { phrase: "soars", score: 2 },
  { phrase: "rallies", score: 2 },
  { phrase: "jumps", score: 2 },
  { phrase: "gains", score: 2 },
  { phrase: "expands", score: 1 },
  { phrase: "growth", score: 1 },
  { phrase: "improves", score: 1 },
  { phrase: "strengthens", score: 1 },
  { phrase: "bullish", score: 2 },
  { phrase: "positive", score: 1 },
  { phrase: "strong demand", score: 2 },
  { phrase: "increases dividend", score: 2 },
  { phrase: "initiates dividend", score: 2 },
  { phrase: "approves buyback", score: 2 },
  { phrase: "secures funding", score: 1 },
  { phrase: "wins contract", score: 2 },
  { phrase: "acquisition", score: 2 },
  { phrase: "merger", score: 2 },
  { phrase: "regulatory approval", score: 2 },
  { phrase: "launches product", score: 2 },
  { phrase: "launches service", score: 2 },
  { phrase: "outperforms", score: 2 },
  { phrase: "posts profit", score: 2 },
  { phrase: "returns to profit", score: 2 },
  { phrase: "rebound", score: 2 },
  { phrase: "recovery", score: 2 },
  { phrase: "restores", score: 1 },
  { phrase: "recovers", score: 1 },
  { phrase: "confirms uptrend", score: 2 },
  { phrase: "confirms support", score: 1 },
  { phrase: "receives investment", score: 1 },
  { phrase: "new partnership", score: 1 },
  { phrase: "positive outlook", score: 2 },
  { phrase: "resumes growth", score: 1 },
  { phrase: "raises target", score: 1 },
  { phrase: "raises price target", score: 1 },
  { phrase: "initiates coverage with buy", score: 2 },
  { phrase: "initiates with outperform", score: 2 },
  { phrase: "initiates with overweight", score: 2 },
  { phrase: "announces buyback", score: 2 },
  { phrase: "announces dividend", score: 2 },
  { phrase: "increases forecast", score: 1 },
  { phrase: "improves rating", score: 1 },
  { phrase: "upward revision", score: 1 },
  { phrase: "raises eps", score: 2 },
  { phrase: "raises revenue", score: 2 },
  { phrase: "reaffirms guidance", score: 1 },
  { phrase: "offers upbeat forecast", score: 1 },
  { phrase: "restores dividend", score: 1 },
  { phrase: "secures approval", score: 1 },
  { phrase: "posts record sales", score: 2 },
  { phrase: "posts record revenue", score: 2 },
  { phrase: "posts record earnings", score: 2 },
  { phrase: "accelerates growth", score: 1 },
  { phrase: "acquires", score: 2 },
  { phrase: "completes acquisition", score: 2 },
  { phrase: "strategic alliance", score: 1 },
  { phrase: "strategic partnership", score: 1 },
  { phrase: "approved", score: 1 },
  { phrase: "receives approval", score: 1 },
  { phrase: "receives clearance", score: 1 },
  { phrase: "fda approval", score: 2 },
  { phrase: "launches ipo", score: 1 },
  { phrase: "listed on exchange", score: 1 },
  { phrase: "positive trial results", score: 2 },
  { phrase: "breakthrough", score: 2 },
  { phrase: "wins lawsuit", score: 1 },
  { phrase: "settles favorably", score: 1 },
  { phrase: "positive earnings", score: 2 },
  { phrase: "positive surprise", score: 2 },
  { phrase: "strong performance", score: 2 },
  { phrase: "robust results", score: 2 },
  { phrase: "unexpected gain", score: 1 },
  { phrase: "unexpected profit", score: 1 },
  { phrase: "unexpectedly strong", score: 2 },
  { phrase: "turnaround", score: 2 },
  { phrase: "comeback", score: 1 },
  { phrase: "initiates share buyback", score: 2 },
  { phrase: "receives grant", score: 1 },
  { phrase: "receives award", score: 1 },
  { phrase: "wins award", score: 1 },
  { phrase: "wins bid", score: 1 },
  { phrase: "secures deal", score: 2 },
  { phrase: "signs agreement", score: 1 },
  { phrase: "receives order", score: 1 },
  { phrase: "new customer", score: 1 },
  { phrase: "expanding footprint", score: 2 },
  { phrase: "expanding globally", score: 2 },
  { phrase: "expanding internationally", score: 2 },
  { phrase: "expanding market", score: 1 },
  { phrase: "expanding capacity", score: 1 },
  { phrase: "raises funding", score: 1 },
  { phrase: "attracts investment", score: 1 },
  { phrase: "secures investment", score: 1 },
  { phrase: "backs", score: 1 },
  { phrase: "endorsed", score: 1 },
  { phrase: "high demand", score: 2 },
  { phrase: "record demand", score: 2 },
  { phrase: "unveils", score: 1 },
  { phrase: "introduces", score: 1 },
  { phrase: "debuts", score: 1 },
  { phrase: "rolls out", score: 1 },
  { phrase: "clinches deal", score: 1 },
  { phrase: "delivers strong", score: 1 },
  { phrase: "delivers record", score: 1 },
  { phrase: "surpasses", score: 1 },
  { phrase: "smashes", score: 1 },
  { phrase: "crushes", score: 1 },
  { phrase: "outpaces", score: 1 },
  { phrase: "improves margins", score: 1 },
  { phrase: "increases margins", score: 1 },
  { phrase: "boosts", score: 1 },
  { phrase: "boosts guidance", score: 1 },
  { phrase: "extends rally", score: 1 },
  { phrase: "continues rally", score: 1 },
  { phrase: "sustained growth", score: 1 },
  { phrase: "new product launch", score: 2 },
  { phrase: "expansion plans", score: 2 },
  { phrase: "profit up", score: 2 },
  { phrase: "revenue up", score: 2 },
  { phrase: "new highs", score: 2 },
  { phrase: "upgrades outlook", score: 2 },
  { phrase: "project approved", score: 2 },
  { phrase: "granted approval", score: 2 },
  { phrase: "accelerating growth", score: 2 },
  { phrase: "institutional buying", score: 2 },
  { phrase: "bullish guidance", score: 2 },
  { phrase: "hikes dividend", score: 2 },
  { phrase: "hikes forecast", score: 2 },
  { phrase: "raises price objective", score: 2 },
  { phrase: "initiates outperform", score: 2 },
  { phrase: "initiates buy", score: 2 },
  { phrase: "share repurchase", score: 2 },

  // --- Bearish phrases ---
  { phrase: "profit warning", score: -2 },
  { phrase: "profit slides", score: -2 },
  { phrase: "earnings slump", score: -2 },
  { phrase: "profits tumble", score: -2 },
  { phrase: "weak forecast", score: -2 },
  { phrase: "downgrade risk", score: -2 },
  { phrase: "loses market share", score: -2 },
  { phrase: "negative sentiment", score: -1 },
  { phrase: "market underperformance", score: -2 },
  { phrase: "capital outflow", score: -1 },
  { phrase: "weak fundamentals", score: -1 },
  { phrase: "fragile results", score: -1 },
  { phrase: "shrinking trajectory", score: -2 },
  { phrase: "dividend cut", score: -2 },
  { phrase: "misses revenue target", score: -2 },
  { phrase: "cash flow declines", score: -2 },
  { phrase: "margin erosion", score: -2 },
  { phrase: "multi-year low", score: -2 },
  { phrase: "demand destruction", score: -2 },
  { phrase: "lags industry", score: -2 },
  { phrase: "margin contraction", score: -1 },
  { phrase: "cuts capital", score: -1 },
  { phrase: "lost contracts", score: -1 },
  { phrase: "loses clients", score: -1 },
  { phrase: "legal setback", score: -1 },
  { phrase: "industry laggard", score: -2 },
  { phrase: "price target lowered", score: -1 },
  { phrase: "share price drops", score: -2 },
  { phrase: "shrinking operations", score: -1 },
  { phrase: "capacity reduction", score: -1 },
  { phrase: "negative cash flow", score: -2 },
  { phrase: "cash reserves fall", score: -1 },
  { phrase: "debt increased", score: -1 },
  { phrase: "failed investment", score: -2 },
  { phrase: "shrinking portfolio", score: -1 },
  { phrase: "notable losses", score: -1 },
  { phrase: "underweight rating", score: -1 },
  { phrase: "downward momentum", score: -2 },
  { phrase: "sustained selloff", score: -2 },
  { phrase: "losing market share", score: -2 },
  { phrase: "business contraction", score: -1 },
  { phrase: "unfavorable ruling", score: -1 },
  { phrase: "unfavorable conditions", score: -1 },
  { phrase: "record-breaking losses", score: -2 },
  { phrase: "worse than forecast", score: -2 },
  { phrase: "lowered guidance", score: -2 },
  { phrase: "cut estimates", score: -1 },
  { phrase: "negative revisions", score: -1 },
  { phrase: "falling profits", score: -2 },
  { phrase: "misses forecasts", score: -2 },
  { phrase: "single-digit growth", score: -1 },
  { phrase: "persistent losses", score: -1 },
  { phrase: "concentration risk", score: -1 },
  { phrase: "decreased market cap", score: -2 },
  { phrase: "market pessimism", score: -1 },
  { phrase: "bearish reversal", score: -2 },
  { phrase: "losing new deals", score: -2 },
  { phrase: "dividend suspension", score: -2 },
  { phrase: "credit downgrade", score: -1 },
  { phrase: "downbeat projections", score: -2 },
  { phrase: "obsolete products", score: -2 },
  { phrase: "weak performance", score: -2 },
  { phrase: "industry loss", score: -1 },
  { phrase: "lower sales momentum", score: -2 },
  { phrase: "new lows recorded", score: -2 },
  { phrase: "selloff", score: -2 },
  { phrase: "analyst downgrade", score: -2 },
  { phrase: "underweight recommendation", score: -1 },
  { phrase: "bearish momentum", score: -2 },
  { phrase: "shipment delays", score: -2 },
  { phrase: "shrinking presence", score: -1 },
  { phrase: "declining order book", score: -2 },
  { phrase: "negative earnings surprise", score: -2 },
  { phrase: "product recall", score: -2 },
  { phrase: "shrinking customer base", score: -2 },
  { phrase: "market exit", score: -2 },
  { phrase: "revenue deceleration", score: -2 },
  { phrase: "unfavorable trend", score: -1 },
  { phrase: "weak balance sheet", score: -2 },
  { phrase: "falling asset value", score: -1 },
  { phrase: "contract loss", score: -2 },
  { phrase: "reduced liquidity", score: -2 },
  { phrase: "lowering forecasts", score: -1 },
  { phrase: "quarterly loss", score: -2 },
  { phrase: "lower guidance", score: -2 },
  { phrase: "unsustainable losses", score: -2 },
  { phrase: "cash burn", score: -1 },
  { phrase: "industry underperformance", score: -2 },
  { phrase: "market exit announced", score: -1 },
  { phrase: "declining sales", score: -2 },
  { phrase: "shareholder dilution", score: -1 },
  { phrase: "inconsistent profitability", score: -1 },
  { phrase: "shrinking backlog", score: -1 },
  { phrase: "worst-in-class", score: -2 },
  { phrase: "sector laggard", score: -2 },
  { phrase: "shrinking customer reach", score: -1 },
  { phrase: "failed strategy", score: -1 },
  { phrase: "narrowing footprint", score: -1 },
  { phrase: "all-time low", score: -2 },
  { phrase: "weak order intake", score: -2 },
  { phrase: "lower efficiency", score: -1 },
  { phrase: "operational setbacks", score: -1 },
  { phrase: "downside risk", score: -2 },
  { phrase: "negative institutional outlook", score: -1 },
  { phrase: "growth halt", score: -1 },
  { phrase: "pipeline contraction", score: -1 },
  { phrase: "margin decline", score: -1 },
  { phrase: "shrinking outlook", score: -2 },
  { phrase: "profitability warning", score: -2 },
  { phrase: "demand drop", score: -2 },
  { phrase: "digital disruption", score: -1 },
  { phrase: "dividend reduction", score: -2 },
  { phrase: "order book shrinks", score: -1 },
  { phrase: "net loss", score: -2 },
  { phrase: "pipeline delay", score: -1 },
  { phrase: "shareholder loss", score: -2 },
  { phrase: "earnings miss", score: -2 },
  { phrase: "underperforming", score: -2 },
  { phrase: "brand damage", score: -1 },
  { phrase: "long-term losses", score: -1 },
  { phrase: "cuts projection", score: -1 },
  { phrase: "dark outlook", score: -2 },
  { phrase: "negative sentiment shift", score: -1 },
  { phrase: "downtrend", score: -2 },
  { phrase: "exiting markets", score: -1 },
  { phrase: "market share loss", score: -1 },
  { phrase: "negative outflow", score: -1 },
  { phrase: "shrinking engine", score: -2 },
  { phrase: "lowered estimate", score: -1 },
  { phrase: "reduced returns", score: -1 },
  { phrase: "net loss increases", score: -2 },
  { phrase: "declining EPS", score: -2 },
  { phrase: "lower utilization", score: -1 },
  { phrase: "lower asset quality", score: -1 },
  { phrase: "cash flow negative", score: -2 },
  { phrase: "undiversified loss", score: -1 },
  { phrase: "innovation lag", score: -1 },
  { phrase: "shrinking platform", score: -1 },
  { phrase: "declining segment", score: -1 },
  { phrase: "net profit falls", score: -2 },
  { phrase: "earnings per share down", score: -2 },
  { phrase: "project losses", score: -1 },
  { phrase: "weak liquidity", score: -2 },
  { phrase: "outlook downgrade", score: -1 },
  { phrase: "lower occupancy", score: -1 },
  { phrase: "partnership dissolves", score: -1 },
  { phrase: "worsened forecast", score: -1 },
  { phrase: "demand collapse", score: -2 },
  { phrase: "market contraction", score: -1 },
  { phrase: "declining sales trend", score: -1 },
  { phrase: "asset divestiture", score: -1 },
  { phrase: "vulnerability", score: -1 },
  { phrase: "unfavorable forecast", score: -1 },
  { phrase: "margin loss", score: -1 },
  { phrase: "negative guidance", score: -2 },
  { phrase: "margin compression", score: -1 },
  { phrase: "revenue shrinkage", score: -1 },
  { phrase: "weak fundamentals", score: -2 },
  { phrase: "loss capital", score: -1 },
  { phrase: "falling EPS", score: -2 },
  { phrase: "missed guidance", score: -2 },
  { phrase: "top-line decline", score: -2 },
  { phrase: "bottom-line decline", score: -2 },
  { phrase: "shareholder value erosion", score: -1 },
  { phrase: "falling asset prices", score: -1 },
  { phrase: "market laggard", score: -2 },
  { phrase: "capital depreciation", score: -1 },
  { phrase: "negative net income", score: -2 },
  { phrase: "record-breaking losses", score: -2 },
  { phrase: "shrinking workforce", score: -1 },
  { phrase: "distribution terminated", score: -1 },
  { phrase: "brand contraction", score: -1 },
  { phrase: "discounted valuation", score: -1 },
  { phrase: "industry penalty", score: -1 },
  { phrase: "investor flight", score: -2 },
  { phrase: "reduced investment", score: -1 },
  { phrase: "failed launch", score: -2 },
  { phrase: "under-delivers", score: -2 },
  { phrase: "misses target", score: -2 },
  { phrase: "negative direction", score: -1 },
  { phrase: "falling revenue", score: -2 },
  { phrase: "weak pipeline", score: -1 },
  { phrase: "thin pipeline", score: -2 },
  { phrase: "soft quarter", score: -1 },
  { phrase: "reduced cash generation", score: -1 },
  { phrase: "lost business", score: -1 },
  { phrase: "market apathy", score: -1 },
  { phrase: "business stagnation", score: -1 },
  { phrase: "consistent underperformance", score: -2 },
  { phrase: "stagnant growth", score: -1 },
  { phrase: "plunged", score: -2 },
  { phrase: "bearish sentiment", score: -1 },
  { phrase: "project cancelled", score: -2 },
  { phrase: "capital outflow", score: -1 },
  { phrase: "industry headwinds", score: -1 },
  { phrase: "increased leverage", score: -1 },
  { phrase: "profit contraction", score: -2 },
  { phrase: "credit negative", score: -1 },
  { phrase: "profit misses", score: -2 },
  { phrase: "weak franchise", score: -1 },
  { phrase: "operational breakdown", score: -1 },
  { phrase: "synergy loss", score: -1 },
  { phrase: "cost overruns", score: -1 },
  { phrase: "asset depreciation", score: -1 },
  { phrase: "record operating loss", score: -2 },
  { phrase: "credit rating downgrade", score: -1 },
  { phrase: "operational decline", score: -1 },
  { phrase: "product recall", score: -2 },
  { phrase: "revenue deterioration", score: -1 },
  { phrase: "asset write-down", score: -1 },
  { phrase: "portfolio contraction", score: -1 },
  { phrase: "revenue misses", score: -2 },
  { phrase: "contract loss", score: -1 },
  { phrase: "capital loss", score: -1 },
  { phrase: "dilutive acquisition", score: -2 },
  { phrase: "diminished offering", score: -1 },
  { phrase: "capital withdrawal", score: -1 },
  { phrase: "operational inefficiency", score: -1 },
  { phrase: "operating loss", score: -1 },
  { phrase: "reduced utilization", score: -1 },
  { phrase: "lower volumes", score: -1 },
  { phrase: "revenue drag", score: -1 },
  { phrase: "share price depreciation", score: -2 },
  { phrase: "breaks support", score: -2 },
  { phrase: "analyst reiterates sell", score: -2 },
  { phrase: "initiates coverage sell", score: -2 },
  { phrase: "order intake decline", score: -2 },
  { phrase: "shrinking supplier base", score: -1 },
  { phrase: "weakened asset quality", score: -1 },
  { phrase: "falling sales", score: -2 },
  { phrase: "profit margin compression", score: -2 },
  { phrase: "net income shrinks", score: -2 },
  { phrase: "new troughs", score: -2 }
  { phrase: "misses expectations", score: -2 },
  { phrase: "misses estimates", score: -2 },
  { phrase: "falls short", score: -2 },
  { phrase: "misses forecast", score: -2 },
  { phrase: "cuts outlook", score: -2 },
  { phrase: "cuts guidance", score: -2 },
  { phrase: "downgrades", score: -2 },
  { phrase: "record low", score: -2 },
  { phrase: "record loss", score: -2 },
  { phrase: "weak quarter", score: -2 },
  { phrase: "slump", score: -2 },
  { phrase: "plunges", score: -2 },
  { phrase: "tumbles", score: -2 },
  { phrase: "slides", score: -2 },
  { phrase: "drops", score: -2 },
  { phrase: "loses", score: -2 },
  { phrase: "contraction", score: -2 },
  { phrase: "declines", score: -2 },
  { phrase: "deteriorates", score: -2 },
  { phrase: "weakens", score: -2 },
  { phrase: "bearish", score: -2 },
  { phrase: "negative", score: -1 },
  { phrase: "weak demand", score: -2 },
  { phrase: "cuts dividend", score: -2 },
  { phrase: "suspends dividend", score: -2 },
  { phrase: "cancels buyback", score: -2 },
  { phrase: "shrinks operations", score: -2 },
  { phrase: "loses contract", score: -2 },
  { phrase: "failed acquisition", score: -2 },
  { phrase: "regulatory setback", score: -2 },
  { phrase: "product recall", score: -2 },
  { phrase: "service outage", score: -2 },
  { phrase: "underperforms", score: -2 },
  { phrase: "posts loss", score: -2 },
  { phrase: "posts decline", score: -2 },
  { phrase: "returns to loss", score: -2 },
  { phrase: "downturn", score: -2 },
  { phrase: "recession", score: -2 },
  { phrase: "downgraded", score: -2 },
  { phrase: "faces lawsuit", score: -2 },
  { phrase: "investigation", score: -2 },
  { phrase: "probe", score: -2 },
  { phrase: "regulatory probe", score: -2 },
  { phrase: "delays", score: -2 },
  { phrase: "delay in", score: -2 },
  { phrase: "delayed", score: -2 },
  { phrase: "missed deadline", score: -2 },
  { phrase: "withdraws guidance", score: -2 },
  { phrase: "withdraws outlook", score: -2 },
  { phrase: "negative outlook", score: -2 },
  { phrase: "lowers target", score: -2 },
  { phrase: "lowers price target", score: -2 },
  { phrase: "initiates coverage with sell", score: -2 },
  { phrase: "initiates with underperform", score: -2 },
  { phrase: "initiates with underweight", score: -2 },
  { phrase: "announces layoff", score: -2 },
  { phrase: "cutting jobs", score: -2 },
  { phrase: "job cuts", score: -2 },
  { phrase: "reduces workforce", score: -2 },
  { phrase: "reducing staff", score: -2 },
  { phrase: "cuts forecast", score: -2 },
  { phrase: "lowers forecast", score: -2 },
  { phrase: "reduces eps", score: -2 },
  { phrase: "reduces revenue", score: -2 },
  { phrase: "downward revision", score: -2 },
  { phrase: "misses eps", score: -2 },
  { phrase: "misses revenue", score: -2 },
  { phrase: "cuts rating", score: -2 },
  { phrase: "downgrades rating", score: -2 },
  { phrase: "earnings warning", score: -2 },
  { phrase: "negative earnings", score: -2 },
  { phrase: "negative surprise", score: -2 },
  { phrase: "weak performance", score: -2 },
  { phrase: "disappointing results", score: -2 },
  { phrase: "unexpected loss", score: -2 },
  { phrase: "unexpected decline", score: -2 },
  { phrase: "unexpectedly weak", score: -2 },
  { phrase: "bankruptcy", score: -3 },
  { phrase: "files for bankruptcy", score: -3 },
  { phrase: "chapter 11", score: -2 },
  { phrase: "restructuring", score: -2 },
  { phrase: "default", score: -2 },
  { phrase: "missed payment", score: -2 },
  { phrase: "defaults on", score: -2 },
  { phrase: "misses coupon", score: -2 },
  { phrase: "misses payment", score: -2 },
  { phrase: "investigated", score: -2 },
  { phrase: "fined", score: -2 },
  { phrase: "penalized", score: -2 },
  { phrase: "lawsuit filed", score: -2 },
  { phrase: "settles unfavorably", score: -2 },
  { phrase: "loses lawsuit", score: -2 },
  { phrase: "loses bid", score: -2 },
  { phrase: "loses order", score: -2 },
  { phrase: "customer loss", score: -2 },
  { phrase: "loses customer", score: -2 },
  { phrase: "recall", score: -2 },
  { phrase: "product failure", score: -2 },
  { phrase: "service failure", score: -2 },
  { phrase: "market contraction", score: -2 },
  { phrase: "shrinking market", score: -2 },
  { phrase: "market exit", score: -2 },
  { phrase: "exits market", score: -2 },
  { phrase: "closes operations", score: -2 },
  { phrase: "facility closure", score: -2 },
  { phrase: "plant closure", score: -2 },
  { phrase: "shuts down", score: -2 },
  { phrase: "suspends operations", score: -2 },
  { phrase: "halts operations", score: -2 },
  { phrase: "cuts production", score: -2 },
  { phrase: "reduces capacity", score: -2 },
  { phrase: "cutbacks", score: -2 },
  { phrase: "warns", score: -2 },
  { phrase: "warning", score: -2 },
  { phrase: "regulatory action", score: -2 },
  { phrase: "regulatory ban", score: -2 },
  { phrase: "banned", score: -2 },
  { phrase: "delisted", score: -2 },
  { phrase: "trading halt", score: -2 },
  { phrase: "share suspension", score: -2 },
  { phrase: "fraud", score: -3 },
  { phrase: "scandal", score: -3 },
  { phrase: "corruption", score: -2 },
  { phrase: "whistleblower", score: -2 },
  { phrase: "embezzlement", score: -2 },
  { phrase: "data breach", score: -2 },
  { phrase: "hack", score: -2 },
  { phrase: "cyberattack", score: -2 },
  { phrase: "layoffs", score: -2 },
  { phrase: "retrenchment", score: -2 },
  { phrase: "furlough", score: -2 },
  { phrase: "strike", score: -2 },
  { phrase: "walkout", score: -2 },
  { phrase: "labor dispute", score: -2 },
  { phrase: "union action", score: -2 },
  { phrase: "supply shortage", score: -2 },
  { phrase: "supply disruption", score: -2 },
  { phrase: "inventory build", score: -2 },
  { phrase: "overcapacity", score: -2 },
  { phrase: "misses deadline", score: -2 },
  { phrase: "delays launch", score: -2 },
  { phrase: "delays approval", score: -2 },
  { phrase: "suspends dividend", score: -2 },
  { phrase: "cuts dividend", score: -2 },
  { phrase: "reduces dividend", score: -2 },
  { phrase: "suspends payment", score: -2 },
  { phrase: "cuts payment", score: -2 },
  { phrase: "reduces payment", score: -2 },
  { phrase: "pulls product", score: -2 },
  { phrase: "discontinues", score: -2 },
  { phrase: "terminated", score: -2 },
  { phrase: "termination", score: -2 },
  { phrase: "cancels", score: -2 },
  { phrase: "cancellation", score: -2 },
  { phrase: "sues", score: -2 },
  { phrase: "faces charges", score: -2 },
  { phrase: "criminal charges", score: -2 },
  { phrase: "civil charges", score: -2 },
  { phrase: "regulatory fine", score: -2 },
  { phrase: "antitrust investigation", score: -2 },
  { phrase: "delisting risk", score: -2 },
  { phrase: "shareholder lawsuit", score: -2 },
  { phrase: "profit plunges", score: -2 },
  { phrase: "profit falls", score: -2 },
  { phrase: "profit down", score: -2 },
  { phrase: "revenue down", score: -2 },
  { phrase: "income down", score: -2 },
  { phrase: "cuts jobs", score: -2 },
  { phrase: "mass layoffs", score: -2 },
  { phrase: "exodus", score: -2 },
  { phrase: "leadership shakeup", score: -2 },
  { phrase: "insider selling", score: -2 },
  { phrase: "restatement", score: -2 },
  { phrase: "restates earnings", score: -2 },
  { phrase: "audit issue", score: -2 },
  { phrase: "governance issue", score: -2 },
  { phrase: "missed payment", score: -2 },
  { phrase: "dividend cut", score: -2 },
  { phrase: "interest rate hike", score: -1 },
  { phrase: "policy tightening", score: -1 },
  { phrase: "geopolitical tension", score: -2 },
  { phrase: "trade war", score: -2 },
  { phrase: "tariff imposed", score: -2 },
  { phrase: "currency devaluation", score: -2 },
  { phrase: "inflation surge", score: -2 },
  { phrase: "stagflation", score: -2 },
  { phrase: "systemic risk", score: -2 },
  { phrase: "market rout", score: -2 },
  { phrase: "market crash", score: -3 }
];

// Fallback single word/short phrase lists
const fallbackBullish = [
  "soar", "rise", "gain", "surge", "up", "record", "growth", "strong", "bull", "beat", "rally", "jump", "increase", "expand", "rebound", "outperform", "profit", "boost", "improve", "positive", "win", "approve", "acquire", "secure", "recover", "comeback", "dividend", "buyback", "milestone", "partnership", "award", "launch", "achievement"
];
const fallbackBearish = [
  "fall", "drop", "decline", "down", "slump", "loss", "weak", "bear", "miss", "plunge", "crash", "decrease", "layoff", "recall", "probe", "cut", "warn", "negative", "default", "investigation", "lawsuit", "delay", "downgrade", "fined", "scandal", "suspend", "terminate", "halt", "shut", "strike", "bankruptcy", "restatement", "outage"
];

// Main function
function getSentiment(headline) {
  const text = headline.toLowerCase();
  let score = 0;

  for (const { phrase, score: phraseScore } of phraseSentiments) {
    if (text.includes(phrase)) score += phraseScore;
  }

  if (score === 0) {
    fallbackBullish.forEach(word => { if (text.includes(word)) score += 1; });
    fallbackBearish.forEach(word => { if (text.includes(word)) score -= 1; });
  }

  if (score > 0) return "Bullish";
  if (score < 0) return "Bearish";
  return "Neutral";
}
